# Font
SMALL_FONT_SIZE = 12
MEDIUM_FONT_SIZE = 16
LARGE_FONT_SIZE = 20

# Group Definitions
ADMIN = "ADMIN"
CLINICIAN = "CLINICIAN"
PATIENT = "PATIENT"

# Colour palette (temporary)
DARK_BLUE = 0x1065AB
MEDIUM_BLUE = 0x3A93C3
LIGHT_BLUE = 0x8EC4DE
PALE_BLUE = 0xD1E5F0
