# Generated by Django 6.0.2 on 2026-02-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingequipment',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
