# Generated by Django 6.0.2 on 2026-02-06 15:41

import django_resized.forms
import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='users/default_pfp.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[128, 128], upload_to=user.models.User.profile_picture_path),
        ),
    ]
