# Generated by Django 6.0.2 on 2026-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='font_size_preference',
            field=models.IntegerField(choices=[(12, 'Small'), (16, 'Medium'), (20, 'Large')], default=16),
        ),
    ]
