# Generated by Django 6.0.2 on 2026-03-02 13:22

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_readingequipment_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressuremapreading',
            name='contact_area',
        ),
        migrations.RemoveField(
            model_name='pressuremapreading',
            name='peak_pressure',
        ),
        migrations.AddField(
            model_name='pressuremapreading',
            name='metrics',
            field=models.FileField(blank=True, null=True, upload_to=user.models.PressureMapReading.pressure_reading_path),
        ),
    ]
