# Generated by Django 6.0.2 on 2026-02-09 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_font_size_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='refresh_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PatientClinicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clinician_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinician', to=settings.AUTH_USER_MODEL)),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
