# Generated by Django 6.0.2 on 2026-03-02 15:50

import django_resized.forms
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_pressuremapreading_contact_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressuremapreading',
            name='metrics',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=user.models.PressureMapReading.pressure_reading_path),
        ),
        migrations.AlterField(
            model_name='pressuremapreading',
            name='pressure_reading',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=user.models.PressureMapReading.pressure_reading_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='users/default_pfp.png', force_format=None, keep_meta=True, max_length=512, quality=-1, scale=None, size=[128, 128], upload_to=user.models.User.profile_picture_path),
        ),
    ]
