# Generated by Django 6.0.2 on 2026-02-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_productinfo_refresh_rate_patientclinicians'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientClinicians',
            new_name='PatientClinician',
        ),
    ]
