# Generated by Django 6.0.2 on 2026-03-02 15:02

import uuid
import datetime
from django.db import migrations
from django.conf import settings
from django.core.files import File
from django.contrib.auth.hashers import make_password
import os


class Migration(migrations.Migration):

    def populate_database(apps, schema_editor):
        User = apps.get_model("user", "User")
        Address = apps.get_model("user", "Address")
        ProductInfo = apps.get_model("user", "ProductInfo")
        ReadingEquipment = apps.get_model("user", "ReadingEquipment")
        PressureMapReading = apps.get_model("user", "PressureMapReading")

        users = []
        for i in range(10):
            email = f"user{i}@example.com"

            if User.objects.filter(email=email).exists():
                continue

            address = Address.objects.create(
                fist_line=f"123 Test Street {i}",
                second_line="",
                town="Testville",
                postal_code=f"TEST{i}123"
            )

            user = User.objects.create(
                email=email,
                first_name=f"User{i}",
                last_name="Test",
                phone_number="1234567890",
                date_of_birth=datetime.date(1995, 1, 1),
                address=address,
                role="PATIENT",
                is_active=True,
                is_staff=False,
                is_superuser=False,
                password=make_password("password123"),
            )
            users.append(user)

        product_info = ProductInfo.objects.create(
            model="PressureMatOne",
            manufacturer="Sensore",
            resolution_width=32,
            resolution_height=32,
            refresh_rate=15,
        )

        equipments = []
        for i in range(10):
            equipment = ReadingEquipment.objects.create(
                product_info=product_info,
                serial_number=f"Serial-{i + 1:04d}",
                user=users[i],
            )
            equipments.append(equipment)

        test_data_dir = os.path.join(settings.MEDIA_ROOT, "test_data")

        for i, equipment in enumerate(equipments):
            reading = PressureMapReading.objects.create(
                reading_equipment=equipment
            )

            csv_path = os.path.join(test_data_dir, f"test_data{i}.csv")

            if os.path.exists(csv_path):
                with open(csv_path, "rb") as f:
                    reading.pressure_reading.save(
                        f"test_data{i}.csv",
                        File(f),
                        save=False
                    )

            reading.save()

    dependencies = [
        ('user', '0004_alter_pressuremapreading_metrics_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_database),

    ]
