# Generated by Django 6.0.1 on 2026-03-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_populate_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='fist_line',
            new_name='first_line',
        ),
    ]
