# Generated by Django 6.0.1 on 2026-03-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_populate_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='read_receipt',
        ),
    ]
