# Generated by Django 6.0.1 on 2026-04-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_body_message_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingequipment',
            options={'ordering': ['-user__date_joined']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='pair_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='frame',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
