# Generated by Django 6.0.1 on 2026-04-10 13:04

from django.db import migrations
import hashlib


def generate_pair_key(user_ids):
    sorted_ids = sorted(user_ids)
    raw = f"{sorted_ids[0]}:{sorted_ids[1]}"
    return hashlib.sha256(raw.encode()).hexdigest()


def populate_pair_keys(apps, schema_editor):
    Conversation = apps.get_model('user', 'Conversation')

    for conversation in Conversation.objects.all():
        user_ids = list(conversation.participants.values_list('id', flat=True))

        if len(user_ids) == 2:
            conversation.pair_key = generate_pair_key(user_ids)
            conversation.save(update_fields=['pair_key'])
        else:
            raise Exception(f"Conversation {conversation.id} does not have 2 participants")



class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_readingequipment_options_conversation_pair_key_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_pair_keys)
    ]
