# Generated by Django 6.0.1 on 2026-04-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_populating_conversation_pair_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='pair_key',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
