# Generated by Django 6.0.1 on 2026-04-14 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_conversation_pair_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuremapreading',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='pressure_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='read_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='personalised_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
