# Generated by Django 6.0.1 on 2026-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_conversation_pair_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuremapreading',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='pressure_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='read_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='personalised_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
